spring.application.name=Assignment3
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.url=jdbc:mysql://localhost:3306/nova_events
spring.datasource.username=nova_user
spring.datasource.password=nova_password
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE